drop table T1 if exists;
create table T1 (
  ID   int         generated by default as identity (start with 1) not null,
  NAME varchar(30) not null,
  constraint T1_PK primary key (ID)
);
insert into T1 values (1, 'R&B');