DROP TABLE db_order_item;
COMMIT;
DROP TABLE db_order;
COMMIT;
DROP TABLE db_customer;
COMMIT;
DROP TABLE db_user;
COMMIT;
DROP TABLE db_role;
COMMIT;
DROP TABLE db_product;
COMMIT;
DROP TABLE db_category;
COMMIT;
DROP SEQUENCE seq_id_gen;
COMMIT;
DROP TABLE dual_seq_id_gen;
COMMIT;
